- name: Pull image and create container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_repo }}"
    pull: missing
    published_ports: "{{ host_interface }}:{{ host_port }}:{{ container_port }}"