name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt
    - name: Lint
      run: |
        pip install flake8
        flake8
    - name: Run tests
      run: cd app_python && pytest && cd ..
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: app_python/
        push: true
        tags: mrfired/devops-course:latest
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch only Python app folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: app_python
          sparse-checkout-cone-mode: false
      - name: Move files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv app_python/* .
          rm -rf app_python
          ls -lah
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
